name: Base-Module-tf-action
on:
  pull_request:
    types:
        - closed
        - opened
    branches:
        - main
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
env:
    TF_LOG: INFO
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
jobs:
    ResourceGroup:
      uses: ./.github/workflows/Terraform.yaml
      
      
      # jobs:
      #   build:
      #     runs-on: ubuntu-latest
      #     steps:
      #     - uses: actions/checkout@v2
      #     - name: Run a multi-line script
      #       run: |
      #         echo Add your commands here
      #         echo Use a new line for each command
      #       working-directory: repo     