name: Base-Module-tf-action
on:
  pull_request:
    types:
      - closed
      - opened
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

env:
  TF_LOG: ERROR
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: [resourcegroup]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calling Terraform Flow
        uses: ./.github/workflows/Terraform.yaml
        with:
          calling_job_name: ${{ matrix.job_name }}
          arm_client_id: ${{ env.ARM_CLIENT_ID }}
          arm_client_secret: ${{ env.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ env.ARM_TENANT_ID }}
