name: Base-Module-tf-action
on:
  pull_request:
    types:
        - closed
        - opened
    branches:
        - main
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:

jobs:
    resourcegroup:
      uses: ./.github/workflows/Terraform.yaml
      with:
        calling_job_name: resourcegroup
            