name: Terraform on Specific Directory

on:
  pull_request:
    types:
      - closed
      - opened
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
    inputs:
      target_directory:
        description: 'Specify which directory to run (e.g., resourcegroup, vnet, storage.)'
        required: true
        default: 'resourcegroup'
env:
  TF_LOG: ERROR
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  run-specific-dir:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [resourcegroup, vnet, storage]  # List all possible directories

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform in Selected Directory
        if: ${{ matrix.dir == github.event.inputs.target_directory }}
        working-directory: ${{ matrix.dir }}
        run: |
          echo "Running in ${{ matrix.dir }}"
          ls -Flah
          terraform init
          terraform apply -auto-approve -var-file=${{ matrix.dir }}.tfvars
