name: Terraform Workflow

on:
  workflow_call:
    inputs:
      calling_job_name:
        required: true
        type: string
      ARM_CLIENT_ID:
        required: true
        type: string
      ARM_CLIENT_SECRET:
        required: true
        type: string
      ARM_SUBSCRIPTION_ID:
        required: true
        type: string
      ARM_TENANT_ID:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ inputs.calling_job_name }}
      ARM_CLIENT_ID: ${{ inputs.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ inputs.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ inputs.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ inputs.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.4

      - name: Terraform Init
        run: |
          ls -Flah
          terraform init 

      - name: Terraform Format
        run: |
          ls -Flah
          terraform fmt --recursive

      - name: Terraform Validate
        id: valid
        run: terraform validate

      - name: Terraform Plan
        if: success() && steps.valid.outcome == 'success'
        id: plan
        run: terraform plan 

      - name: Terraform Apply
        if: success() && steps.plan.outcome == 'success'
        run: terraform apply -auto-approve
