name: tf-action
on:
  workflow_call:
    inputs:
      calling_job_name:
        required: true
        type: string
      arm_client_id:
        required: true
        type: string
      arm_client_secret:
        required: true
        type: string
      arm_subscription_id:
        required: true
        type: string
      arm_tenant_id:
        required: true
        type: string

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ inputs.calling_job_name }}
      ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
      ARM_CLIENT_SECRET: ${{ inputs.arm_client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
      ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.4

      - name: Change to working directory
        run: cd ${{ env.WORKING_DIR }} && pwd  # This changes to the specified directory

      - name: Terraform Init
        run: |
          cd ${{ env.WORKING_DIR }} 
          terraform init 

      - name: Terraform Format
        run: |
          cd ${{ env.WORKING_DIR }} 
          terraform fmt --recursive

      - name: Terraform Validate
        id: valid
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform validate

      - name: Terraform Plan
        if: success() && steps.valid.outcome == 'success'
        id: plan
        run: |
          cd ${{ env.WORKING_DIR }}  
          terraform plan 

      - name: Terraform Apply
        if: success() && steps.plan.outcome == 'success'
        run: |
          cd ${{ env.WORKING_DIR }} 
          terraform apply -auto-approve
