name: Terraform Workflow

on:
  workflow_call:
    inputs:
      calling_job_name:
        required: true
        type: string
      ARM_CLIENT_ID:
        required: true
        type: string
      ARM_CLIENT_SECRET:
        required: true
        type: string
      ARM_SUBSCRIPTION_ID:
        required: true
        type: string
      ARM_TENANT_ID:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ${{ inputs.calling_job_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ inputs.ARM_CLIENT_ID }}
          client-secret: ${{ inputs.ARM_CLIENT_SECRET }}
          tenant-id: ${{ inputs.ARM_TENANT_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init 

      - name: Terraform Format
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform fmt --recursive

      - name: Terraform Validate
        working-directory: ${{ env.WORKING_DIR }}
        id: valid
        run: terraform validate

      - name: Terraform Plan
        if: success() && steps.valid.outcome == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        id: plan
        run: terraform plan 

      - name: Terraform Apply
        if: success() && steps.plan.outcome == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve
