name: Run Specific Directory

on:
  workflow_dispatch:
    inputs:
      target_directory:
        description: 'Specify which directory to run (e.g., dir1, dir2, etc.)'
        required: true
        default: 'resourcegroup'

jobs:
  run-specific-dir:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [resourcegroup, vnet, storage]  # List all possible directories

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform in Selected Directory
        if: ${{ matrix.dir == github.event.inputs.target_directory }}
        working-directory: ${{ matrix.dir }}
        run: |
          echo "Running in ${{ matrix.dir }}"
          terraform init
          terraform apply -auto-approve
