name: tf-action
on:
    workflow_call:
      inputs:
        calling_job_name:
          required: true
          type: string
env:
    TF_LOG: ERROR
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
jobs:
    Terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.9.8
            - name: Terraform Init
              run: terraform init 
              
            - name: Terraform Format
              run: |
                ls -Flah
                terraform fmt --recursive
        
            - name: Terraform Validate
              id: valid
              run: terraform validate
              
            - name: Terraform Plan
              if: success() && steps.valid.outcome == 'success'
              id: plan
              run: |
                cd  ${{ inputs.calling_job_name }}
                terraform plan 

            - name: Terraform Apply
              if: success() && steps.plan.outcome == 'success'
              run: terraform apply -auto-approve
